# Generated by Django 4.2.3 on 2023-08-01 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forwarding', '0002_clients_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, unique=True, verbose_name='message theme')),
                ('body', models.TextField(max_length=500, verbose_name='message body')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='message slug')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='transmission name')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='start time for sending')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')])),
                ('status', models.CharField(choices=[('FINISHED', 'Finished'), ('CREATED', 'Created'), ('READY', 'Running'), ('FINISHED_WITH_ERROR', 'Finished Error')], default='CREATED')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='transmission slug')),
                ('is_published', models.BooleanField(default=True)),
                ('clients', models.ManyToManyField(to='forwarding.clients')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forwarding.messages')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transmission',
                'verbose_name_plural': 'Transmission Templates',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last time for send')),
                ('status', models.CharField(choices=[('FINISHED', 'Finished'), ('CREATED', 'Created')], default='CREATED')),
                ('mail_answer', models.CharField(blank=True, default=None, null=True, verbose_name='answer from mailserver')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_of_transmission', to='forwarding.transmission')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
