# Generated by Django 4.2.3 on 2023-08-04 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forwarding', '0003_messages_transmission_statistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'verbose_name': 'Передача', 'verbose_name_plural': 'Шаблоны передач'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(max_length=500, verbose_name='Тело сообщения'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug сообщения'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='theme',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тема сообщения'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='mail_answer',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Ответ от почтового сервера'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='status',
            field=models.CharField(choices=[('FINISHED', 'Finished'), ('CREATED', 'Created')], default='CREATED', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Последнее время отправки'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_of_transmission', to='forwarding.transmission', verbose_name='Передача'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='clients',
            field=models.ManyToManyField(to='forwarding.clients', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], verbose_name='Частота отправки'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forwarding.messages', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug рассылки'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='status',
            field=models.CharField(choices=[('FINISHED', 'Finished'), ('CREATED', 'Created'), ('READY', 'Running'), ('FINISHED_WITH_ERROR', 'Finished Error')], default='CREATED', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала отправки'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название рассылки'),
        ),
    ]
