# Generated by Django 4.2.3 on 2023-08-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forwarding', '0004_alter_messages_options_alter_statistic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmission',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Шаблоны рассылок'},
        ),
    ]
